#!/bin/bash

echo \"First arg length: ${#1}\"
echo \"First arg bytes:\"
echo -n \"$1\" | xxd

if [ \"$1\" = \"crate\" ]; then
    echo \"MATCHED with simple comparison\"
fi

case \"$1\" in
    crate)
        echo \"MATCHED with case\"
        ;;
    *)
        echo \"No case match\"
        ;;
esac
